# coding: utf-8

# flake8: noqa
"""
    Todo API

    A simple Todo API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from todosdk.models.todo import Todo
from todosdk.models.todos_post_request import TodosPostRequest
